// Toàn bộ nội dung JavaScript từ <script> trong file gốc
// Bao gồm các hàm xử lý flashcard, phát âm, AI hội thoại, luyện dịch, thêm từ mới, phần thưởng, sự kiện khởi tạo...
// Bạn chỉ cần copy toàn bộ nội dung <script> và dán vào file này
